version: '2.2'
services:
  vic-elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    command: |
      sh -c 'sysctl -w vm.max_map_count=262144 && /usr/local/bin/docker-entrypoint.sh eswrapper'
    environment:
      #- cluster.name=vic-cluster
      - node.name=vic-elasticsearch-1
      - discovery.type=zen
      - "discovery.zen.ping.unicast.hosts=vic-elasticsearch-2,vic-elasticsearch-3"
      #- discovery.zen.ping.unicast.hosts=elasticsearch-1
      - discovery.zen.minimum_master_nodes=2
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=changeme
      - ALLOW_INSECURE_DEFAULT_TLS_CERT="true"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es--net
#      - external

  vic-elasticsearch-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    command: |
      sh -c 'sysctl -w vm.max_map_count=262144 && /usr/local/bin/docker-entrypoint.sh eswrapper'
    environment:
      #- cluster.name=vic-cluster
      - node.name=vic-elasticsearch-2
      - discovery.type=zen
      - "discovery.zen.ping.unicast.hosts=vic-elasticsearch-1,vic-elasticsearch-3"
      #- discovery.zen.ping.unicast.hosts=elasticsearch1
      - discovery.zen.minimum_master_nodes=2
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=changeme
      - ALLOW_INSECURE_DEFAULT_TLS_CERT="true"
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - es--net
 #     - external

  vic-elasticsearch-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    command: |
      sh -c 'sysctl -w vm.max_map_count=262144 && /usr/local/bin/docker-entrypoint.sh eswrapper'
    environment:
      #- cluster.name=vic-cluster
      - node.name=vic-elasticsearch-3
      - discovery.type=zen
      - "discovery.zen.ping.unicast.hosts=vic-elasticsearch-1,vic-elasticsearch-2"
      #- discovery.zen.ping.unicast.hosts=elasticsearch1
      - discovery.zen.minimum_master_nodes=2
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=changeme
      - ALLOW_INSECURE_DEFAULT_TLS_CERT="true"
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - es--net
#      - external

  logstash:
#    image: docker.elastic.co/logstash/logstash:6.2.3
    image: vic.tpm.com/elk/mylogstash
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
      - "FILESERVER=10.40.206.190:8080"
      - "CONFIGFILE=first-pipeline.yml"
#      - "LOG_LEVEL=debug"
#      - "XPACK_MONITORING_ENABLED"
# https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html
# All environement variables can be found in the link above
# Replace . with _ in the options and convert alphabets to all caps for environment variable name
# These environment variables are written in all capitals, with underscores as word separators
    networks:
      - es--net
#      - external
    depends_on:
      - vic-elasticsearch-1
      - vic-elasticsearch-2
      - vic-elasticsearch-3

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL="http://vic-elasticsearch-1:9200"
# https://www.elastic.co/guide/en/kibana/current/settings.html
# All environment variable for Kibana can be found in the link above
# These environment variables are written in all capitals, with underscores as word separators
    networks:
      - es--net
#      - external
    depends_on:
      - vic-elasticsearch-1
      - vic-elasticsearch-2
      - vic-elasticsearch-3

volumes:
  esdata1:
    driver: vsphere
    driver_opts:
      capacity: 10GB
  esdata2:
    driver: vsphere
    driver_opts:
      capacity: 10GB
  esdata3:
    driver: vsphere
    driver_opts:
      capacity: 10GB

#networks:
#  es--net:
networks:
  es--net:
#  external:
#    external: true

