version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    command: |
      sh -c 'sysctl -w vm.max_map_count=262144 && /usr/local/bin/docker-entrypoint.sh eswrapper'
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - discovery.type=zen
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=changeme
      - ALLOW_INSECURE_DEFAULT_TLS_CERT="true"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  logstash:
#    image: docker.elastic.co/logstash/logstash:6.2.3
    image: vic.tpm.com/elk/mylogstash
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
      - "FILESERVER=10.40.206.190:8080"
      - "CONFIGFILE=first-pipeline.yml"
# https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html
# All environement variables can be found in the link above
# Replace . with _ in the options and convert alphabets to all caps for environment variable name
#      - "LOG_LEVEL=debug"
#      - "XPACK_MONITORING_ENABLED"
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: vsphere

networks:
  esnet:

